language: node_js
os:
  - linux

node_js:
  - 8.11.3
  - 10.8.0

services:
  - docker

branches:
  - master

before_install:
  - docker-compose up -d

install:
  - npm install

script:
  - npm run pkg:build
  - npm run pkg:test

after_success:
  - codecov -t 0f2848b9-8489-4756-84a9-89afa12ce6e6
