version: "3"

networks:
  net-redis:

volumes:
  volume-redis:

services:

  redis:
    image: redis:4.0.6
    networks:
      - net-redis
    ports:
      - "6379:6379"
    volumes:
      - volume-redis:/data
    environment:
      REDIS_PASSWORD: tedis_love_you
    command: ["sh", "-c", 'exec redis-server --requirepass "$$REDIS_PASSWORD"']
